# Generated by Django 2.2.6 on 2019-12-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_abvuser_machine_spare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-published'],
            },
        ),
        migrations.RemoveField(
            model_name='bb',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.DeleteModel(
            name='AbvUser',
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
